// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCKX5ftkTJwsE1pnlR_g7SfLBKFXb4RTpw",
  authDomain: "food-travel-guide.firebaseapp.com",
  projectId: "food-travel-guide",
  storageBucket: "food-travel-guide.firebasestorage.app",
  messagingSenderId: "118382363397",
  appId: "1:118382363397:web:ab634c4a1b78b308a66d6c",
  measurementId: "G-1DP3G9LGYP"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAkDbkjnNxAJSezFGlLNLY-Ldv-x-2IWf0",
    appId: "1:118382363397:android:cf37fdc0dba79b2fa66d6c",
    messagingSenderId: "118382363397",
    projectId: "food-travel-guide",
    storageBucket: "food-travel-guide.firebasestorage.app",
  );
}
